# Generated by Django 5.2.5 on 2025-08-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
            ],
        ),
    ]
